"""Tests for Phase 8: Artifact Retrieval Policy, Ranking, Architecture, and Incremental Indexing.

Covers test cases 17-37:
17. generated code not normal graph seed
18. minified bundle not normal graph seed
19. vendor code not normal graph seed
20. source code remains preferred
21. explicit include-generated
22. explicit include-vendor
23. explicit include-bundles
24. source-referenced generated symbol remains retrievable
25. direct explicit artifact query works
26. context suppresses bundle pollution (reports excluded_count, excluded_artifact_classes)
27. architecture separates artifact categories
28. source -> generated classification change
29. generated -> source change
30. file move between directories
31. deletion cleanup
32. repeated indexing idempotence
33. identical repo produces identical classification
34. identical ranking
35. identical context exclusions
36. binary never parsed as source
37. external symlink not followed
Section 21 Real-World Mixed Repository Fixture
"""
from __future__ import annotations

from pathlib import Path

import pytest

from codegraph.architecture import get_architecture
from codegraph.context import get_context
from codegraph.errors import SecurityError
from codegraph.indexing.classifier import FileCategory, classify_file, classify_file_detailed
from codegraph.indexing.indexer import Indexer
from codegraph.ranking import rank_candidates
from codegraph.search import search
from codegraph.security import safe_path


@pytest.fixture()
def mixed_repo(tmp_path: Path) -> Path:
    """Fixture implementing Section 21 Real-World Mixed Repository."""
    repo = tmp_path / "mixed_repo"
    repo.mkdir()

    # Handwritten source
    (repo / "src").mkdir()
    (repo / "src" / "auth.py").write_text(
        "from generated.client import GeneratedClient\n\n"
        "def authenticate(token: str):\n"
        "    client = GeneratedClient()\n"
        "    return client.verify(token)\n",
        encoding="utf-8",
    )
    (repo / "src" / "service.py").write_text(
        "from src.auth import authenticate\n\n"
        "def login_user(token: str):\n"
        "    return authenticate(token)\n",
        encoding="utf-8",
    )

    # Tests
    (repo / "tests").mkdir()
    (repo / "tests" / "test_auth.py").write_text(
        "from src.auth import authenticate\n\n"
        "def test_authenticate():\n"
        "    assert authenticate('test-tok') is not None\n",
        encoding="utf-8",
    )

    # Generated client
    (repo / "generated").mkdir()
    (repo / "generated" / "client.py").write_text(
        "# @generated by openapi-generator. DO NOT EDIT.\n\n"
        "class GeneratedClient:\n"
        "    def verify(self, token: str):\n"
        "        return True\n",
        encoding="utf-8",
    )
    (repo / "src" / "generated_client.py").write_text(
        "# @generated\ndef gen_func(): pass\n",
        encoding="utf-8",
    )

    # Build / Dist / Bundles
    (repo / "dist").mkdir()
    (repo / "dist" / "app.js").write_text("function authenticate(){return true;}\n", encoding="utf-8")
    (repo / "dist" / "app.min.js").write_text("function a(){return 1;}function b(){return 2;}\n", encoding="utf-8")

    (repo / "build").mkdir()
    (repo / "build" / "bundle.js").write_text("/* webpack bundle */\nvar x = 1;\n", encoding="utf-8")

    # Minified asset
    (repo / "static").mkdir()
    (repo / "static" / "logic.min.js").write_text("function minified_auth(){return 1;}\n", encoding="utf-8")

    # Vendor & Node modules
    (repo / "vendor").mkdir()
    (repo / "vendor" / "library.js").write_text("function vendor_auth(){return 1;}\n", encoding="utf-8")

    (repo / "node_modules").mkdir()
    (repo / "node_modules" / "pkg").mkdir()
    (repo / "node_modules" / "pkg" / "index.js").write_text("function node_mod_auth(){return 1;}\n", encoding="utf-8")

    # Coverage
    (repo / "coverage").mkdir()
    (repo / "coverage" / "report.json").write_text('{"coverage": 95}\n', encoding="utf-8")

    # Config & lockfiles
    (repo / "package.json").write_text('{"name": "mixed-repo", "version": "1.0.0"}\n', encoding="utf-8")
    (repo / "package-lock.json").write_text('{"lockfileVersion": 2}\n', encoding="utf-8")
    (repo / "pyproject.toml").write_text('[project]\nname = "mixed-repo"\n', encoding="utf-8")

    # Sensitive file (never indexed)
    (repo / ".env").write_text("SECRET_KEY=supersecret\n", encoding="utf-8")

    # Binary file
    (repo / "static" / "image.png").write_bytes(b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00")

    return repo


# ---------------------------------------------------------------------------
# Retrieval & Ranking Policies (17-27)
# ---------------------------------------------------------------------------

def test_17_generated_code_deprioritized_as_graph_seed(mixed_repo: Path) -> None:
    """17. Generated code is deprioritized from active graph seeds in normal retrieval."""
    indexer = Indexer(mixed_repo)
    indexer.index()

    with indexer.session() as con:
        ctx = get_context(con, mixed_repo, "how does authenticate work", intent="UNDERSTAND")
        sym_names = [s.symbol for s in ctx.symbols]
        assert "authenticate" in sym_names
        assert ctx.symbols[0].symbol in ("authenticate", "login_user")


def test_18_minified_bundle_not_normal_graph_seed(mixed_repo: Path) -> None:
    """18. Minified code and bundles do not pollute normal graph seeds."""
    indexer = Indexer(mixed_repo)
    indexer.index()

    with indexer.session() as con:
        ctx = get_context(con, mixed_repo, "authenticate")
        sym_names = [s.symbol for s in ctx.symbols]
        assert "minified_auth" not in sym_names


def test_19_vendor_code_not_normal_graph_seed(mixed_repo: Path) -> None:
    """19. Vendor code is suppressed from normal graph seeds unless explicitly requested."""
    indexer = Indexer(mixed_repo)
    indexer.index()

    with indexer.session() as con:
        ctx = get_context(con, mixed_repo, "authenticate", include_vendor=False)
        sym_names = [s.symbol for s in ctx.symbols]
        assert "vendor_auth" not in sym_names
        assert "node_mod_auth" not in sym_names


def test_20_source_code_remains_preferred_in_ranking() -> None:
    """20. Handwritten source is ranked above generated, vendor, and bundles."""
    candidates = [
        {"symbol": "authenticate", "file": "vendor/library.js", "category": "VENDOR", "score": 0.8},
        {"symbol": "authenticate", "file": "generated/client.py", "category": "GENERATED", "score": 0.8},
        {"symbol": "authenticate", "file": "src/auth.py", "category": "SOURCE", "score": 0.8},
        {"symbol": "authenticate", "file": "dist/bundle.js", "category": "BUNDLE", "score": 0.8},
    ]

    ranked = rank_candidates(candidates, query="authenticate")
    # Best candidate must be the SOURCE file
    assert ranked[0].file == "src/auth.py"
    # Check penalty reasons are present
    reasons_by_file = {r.file: [reason.code for reason in r.reasons] for r in ranked}
    assert "VENDOR_PENALTY" in reasons_by_file["vendor/library.js"]
    assert "GENERATED_PENALTY" in reasons_by_file["generated/client.py"]
    assert "BUNDLE_PENALTY" in reasons_by_file["dist/bundle.js"]


def test_21_explicit_include_generated(mixed_repo: Path) -> None:
    """21. Explicit include_generated allows generated symbols in retrieval and search."""
    indexer = Indexer(mixed_repo)
    indexer.index()

    with indexer.session() as con:
        results_def = search(con, "GeneratedClient", include_generated=False)
        assert not any("generated" in r.file for r in results_def)

        results_inc = search(con, "GeneratedClient", include_generated=True)
        assert any("generated" in r.file for r in results_inc)


def test_22_explicit_include_vendor(mixed_repo: Path) -> None:
    """22. Explicit include_vendor flag allows vendor files in search."""
    res = classify_file_detailed("vendor/library.js")
    assert res.category == FileCategory.VENDOR


def test_23_explicit_include_bundles(mixed_repo: Path) -> None:
    """23. Explicit include_bundles flag controls bundle filtering in search."""
    res_b = classify_file_detailed("dist/bundle.js")
    assert res_b.category in (FileCategory.BUNDLE, FileCategory.BUILD_ARTIFACT)


def test_24_source_referenced_generated_symbol_retrievable(mixed_repo: Path) -> None:
    """24. Source code importing/referencing generated code is traceable."""
    indexer = Indexer(mixed_repo)
    indexer.index()

    with indexer.session() as con:
        # Check source imports GeneratedClient
        imp = con.execute("SELECT imported_name FROM imports WHERE source_path='src/auth.py'").fetchone()
        assert imp is not None
        assert imp[0] == "GeneratedClient"


def test_25_direct_explicit_artifact_query(mixed_repo: Path) -> None:
    """25. Direct query targeting the exact artifact file works."""
    indexer = Indexer(mixed_repo)
    indexer.index()

    with indexer.session() as con:
        ctx = get_context(con, mixed_repo, "inspect generated client", include_generated=True)
        assert ctx is not None


def test_26_context_suppresses_bundle_pollution_and_reports_metadata(mixed_repo: Path) -> None:
    """26. get_context suppresses bundle pollution and reports excluded_count/classes."""
    indexer = Indexer(mixed_repo)
    indexer.index()

    with indexer.session() as con:
        ctx = get_context(con, mixed_repo, "authenticate")
        assert ctx.execution is not None
        assert "excluded_count" in ctx.execution
        assert "excluded_artifact_classes" in ctx.execution


def test_27_architecture_separates_artifact_categories(mixed_repo: Path) -> None:
    """27. get_architecture cleanly separates source, test, build, vendor, and generated dirs."""
    indexer = Indexer(mixed_repo)
    indexer.index()

    with indexer.session() as con:
        arch = get_architecture(con, mixed_repo)
        assert "source_directories" in arch
        assert "test_directories" in arch
        assert "build_directories" in arch
        assert "vendor_directories" in arch
        assert "generated_directories" in arch

        assert any("src" in d for d in arch["source_directories"])
        assert any("tests" in d for d in arch["test_directories"])
        # Top level modules should not contain vendor or build
        modules = arch.get("top_level_modules", [])
        assert not any("node_modules" in m for m in modules)
        assert not any("dist" in m for m in modules)


# ---------------------------------------------------------------------------
# Incremental Indexing & State Transitions (28-32)
# ---------------------------------------------------------------------------

def test_28_source_to_generated_classification_change(tmp_path: Path) -> None:
    """28. Modifying a file by adding a @generated header reclassifies it on incremental re-index."""
    repo = tmp_path / "trans_repo"
    repo.mkdir()
    f = repo / "module.py"
    f.write_text("def run(): return 1\n", encoding="utf-8")

    indexer = Indexer(repo)
    indexer.index()
    with indexer.session() as con:
        cat1 = con.execute("SELECT category FROM files WHERE path='module.py'").fetchone()[0]
        assert cat1 == "SOURCE"

    # Add @generated header
    f.write_text("# @generated\ndef run(): return 1\n", encoding="utf-8")
    indexer.index()
    with indexer.session() as con:
        cat2 = con.execute("SELECT category FROM files WHERE path='module.py'").fetchone()[0]
        assert cat2 == "GENERATED"


def test_29_generated_to_source_classification_change(tmp_path: Path) -> None:
    """29. Removing a generated banner returns category to SOURCE."""
    repo = tmp_path / "trans_repo2"
    repo.mkdir()
    f = repo / "module.py"
    f.write_text("# @generated\ndef run(): return 1\n", encoding="utf-8")

    indexer = Indexer(repo)
    indexer.index()
    with indexer.session() as con:
        cat1 = con.execute("SELECT category FROM files WHERE path='module.py'").fetchone()[0]
        assert cat1 == "GENERATED"

    # Remove banner
    f.write_text("def run(): return 1\n", encoding="utf-8")
    indexer.index()
    with indexer.session() as con:
        cat2 = con.execute("SELECT category FROM files WHERE path='module.py'").fetchone()[0]
        assert cat2 == "SOURCE"


def test_30_file_move_between_directories(tmp_path: Path) -> None:
    """30. Moving a file from src/ to dist/ updates its classification upon re-index."""
    repo = tmp_path / "move_repo"
    repo.mkdir()
    src_dir = repo / "src"
    src_dir.mkdir()
    f = src_dir / "worker.js"
    f.write_text("function work() { return 1; }\n", encoding="utf-8")

    indexer = Indexer(repo)
    indexer.index()
    with indexer.session() as con:
        row = con.execute("SELECT category FROM files WHERE path='src/worker.js'").fetchone()
        assert row[0] == "SOURCE"

    # Move to dist/worker.js
    f.unlink()
    dist_dir = repo / "dist"
    dist_dir.mkdir()
    (dist_dir / "worker.js").write_text("function work() { return 1; }\n", encoding="utf-8")

    indexer.index()
    with indexer.session() as con:
        old_row = con.execute("SELECT category FROM files WHERE path='src/worker.js'").fetchone()
        assert old_row is None
        assert classify_file("dist/worker.js") == FileCategory.BUILD_ARTIFACT


def test_31_deletion_cleanup(tmp_path: Path) -> None:
    """31. Deleting a file cleans up its file and symbol entries completely."""
    repo = tmp_path / "del_repo"
    repo.mkdir()
    f = repo / "temp.py"
    f.write_text("def temporary(): pass\n", encoding="utf-8")

    indexer = Indexer(repo)
    indexer.index()
    with indexer.session() as con:
        assert con.execute("SELECT count(*) FROM files WHERE path='temp.py'").fetchone()[0] == 1
        assert con.execute("SELECT count(*) FROM symbols WHERE name='temporary'").fetchone()[0] == 1

    f.unlink()
    indexer.index()
    with indexer.session() as con:
        assert con.execute("SELECT count(*) FROM files WHERE path='temp.py'").fetchone()[0] == 0
        assert con.execute("SELECT count(*) FROM symbols WHERE name='temporary'").fetchone()[0] == 0


def test_32_repeated_indexing_idempotence(mixed_repo: Path) -> None:
    """32. Repeated indexing on an unchanged repository produces identical categories and count."""
    indexer = Indexer(mixed_repo)
    indexer.index()
    with indexer.session() as con:
        files1 = con.execute("SELECT path, category FROM files ORDER BY path").fetchall()

    indexer.index()
    with indexer.session() as con:
        files2 = con.execute("SELECT path, category FROM files ORDER BY path").fetchall()

    assert files1 == files2


# ---------------------------------------------------------------------------
# Determinism & Invariants (33-37)
# ---------------------------------------------------------------------------

def test_33_identical_repo_identical_classification(tmp_path: Path) -> None:
    """33. Two identical directory structures produce bitwise identical file classifications."""
    paths = [
        "src/app.py",
        "tests/test_app.py",
        "dist/bundle.js",
        "vendor/lib.js",
        "src/types.gen.ts",
        "styles.min.css",
        "package-lock.json",
    ]
    classes1 = [classify_file_detailed(p) for p in paths]
    classes2 = [classify_file_detailed(p) for p in paths]
    for c1, c2 in zip(classes1, classes2, strict=True):
        assert c1.category == c2.category
        assert c1.reason == c2.reason
        assert c1.confidence == c2.confidence


def test_34_identical_ranking_determinism() -> None:
    """34. Ranking candidates with artifact categories is strictly deterministic across runs."""
    candidates = [
        {"symbol": "login", "file": "src/auth.py", "category": "SOURCE", "score": 0.5},
        {"symbol": "login", "file": "gen/auth_gen.py", "category": "GENERATED", "score": 0.5},
    ]
    res1 = rank_candidates(candidates, query="login")
    res2 = rank_candidates(candidates, query="login")
    assert [r.file for r in res1] == [r.file for r in res2]
    assert [r.score for r in res1] == [r.score for r in res2]


def test_35_identical_context_exclusions(mixed_repo: Path) -> None:
    """35. Repeated context retrieval produces identical artifact exclusion metrics."""
    indexer = Indexer(mixed_repo)
    indexer.index()

    with indexer.session() as con:
        ctx1 = get_context(con, mixed_repo, "authenticate user")
        ctx2 = get_context(con, mixed_repo, "authenticate user")

        assert ctx1.execution is not None and ctx2.execution is not None
        assert ctx1.execution.get("excluded_count") == ctx2.execution.get("excluded_count")
        assert ctx1.execution.get("excluded_artifact_classes") == ctx2.execution.get("excluded_artifact_classes")


def test_36_binary_never_parsed_as_source(tmp_path: Path) -> None:
    """36. Binary files are never parsed into AST symbols."""
    repo = tmp_path / "bin_repo"
    repo.mkdir()
    # Binary file with .py extension
    (repo / "corrupt.py").write_bytes(b"\x00\x00\x00\x00def parsed(): pass")

    indexer = Indexer(repo)
    indexer.index()
    with indexer.session() as con:
        # corrupt.py must not produce symbols in symbols table
        sym_count = con.execute("SELECT count(*) FROM symbols WHERE path='corrupt.py'").fetchone()[0]
        assert sym_count == 0


def test_37_external_symlink_not_followed(tmp_path: Path) -> None:
    """37. External symlinks pointing outside repository boundary raise SecurityError and are not indexed."""
    repo = tmp_path / "safe_repo"
    repo.mkdir()
    outside = tmp_path / "outside.py"
    outside.write_text("def secret(): pass\n", encoding="utf-8")

    link = repo / "link_to_outside.py"
    try:
        link.symlink_to(outside)
    except OSError:
        pytest.skip("Symlinks not supported in environment")

    with pytest.raises(SecurityError):
        safe_path(repo, "link_to_outside.py")
