"""Tests for Phase 8: Artifact, Generated Code & Bundle Classification.

Verifies deterministic, explainable classification of repository files into:
- SOURCE
- TEST
- GENERATED
- BUILD_ARTIFACT
- BUNDLE
- MINIFIED
- VENDOR
- CONFIG
- BINARY
- UNKNOWN
"""
from __future__ import annotations

from codegraph.indexing.classifier import (
    FileCategory,
    classify_file,
    classify_file_detailed,
)


def test_01_handwritten_source() -> None:
    """1. Handwritten source files (.py, .ts, .js) classify as SOURCE."""
    res_py = classify_file_detailed("src/services/auth.py", "def login(): pass")
    assert res_py.category == FileCategory.SOURCE
    assert res_py.reason == "handwritten_source_file"
    assert res_py.confidence == "HIGH"

    res_ts = classify_file_detailed("src/client.ts", "export function connect() {}")
    assert res_ts.category == FileCategory.SOURCE
    assert res_ts.reason == "handwritten_source_file"


def test_02_generated_header_banners() -> None:
    """2. Files with generated banners (@generated, DO NOT EDIT, etc.) classify as GENERATED."""
    py_header = "# @generated by tool. Do not edit.\ndef api_call(): pass"
    res_py = classify_file_detailed("src/api_client.py", py_header)
    assert res_py.category == FileCategory.GENERATED
    assert res_py.reason == "generated_header_banner"
    assert "api_client.py" in str(res_py.evidence) or "@generated" in str(res_py.evidence)

    ts_header = "// Code generated by protoc-gen-ts. DO NOT EDIT.\nexport interface Query {}"
    res_ts = classify_file_detailed("src/proto.ts", ts_header)
    assert res_ts.category == FileCategory.GENERATED
    assert res_ts.reason == "generated_header_banner"

    auto_gen = "/* AUTO-GENERATED FILE. DO NOT MODIFY. */\nclass Schema {}"
    res_auto = classify_file_detailed("src/schema.js", auto_gen)
    assert res_auto.category == FileCategory.GENERATED
    assert res_auto.reason == "generated_header_banner"


def test_03_generated_path_and_filename() -> None:
    """3. Filenames matching generated patterns or generated directories classify as GENERATED."""
    res1 = classify_file_detailed("src/models/user_pb2.py")
    assert res1.category == FileCategory.GENERATED
    assert "generated_filename_pattern" in res1.reason

    res2 = classify_file_detailed("src/generated/client.py")
    assert res2.category == FileCategory.GENERATED
    assert "generated_directory_path" in res2.reason

    res3 = classify_file_detailed("src/types/schema.gen.ts")
    assert res3.category == FileCategory.GENERATED
    assert "generated_filename_pattern" in res3.reason

    res4 = classify_file_detailed("src/types/index.d.ts")
    assert res4.category == FileCategory.GENERATED
    assert "generated_filename_pattern" in res4.reason


def test_04_dist_artifact() -> None:
    """4. Files under dist/ classify as BUILD_ARTIFACT."""
    res = classify_file_detailed("dist/app.js")
    assert res.category == FileCategory.BUILD_ARTIFACT
    assert res.reason.startswith("known_build_output_path")
    assert "dist" in res.evidence


def test_05_build_artifacts() -> None:
    """5. Files under build/, out/, target/, .next/ classify as BUILD_ARTIFACT."""
    for path in [
        "build/bundle.js",
        "out/main.js",
        "target/debug/app",
        ".next/server/pages/index.js",
        "coverage/lcov-report/index.html",
        "src/__pycache__/app.cpython-311.pyc",
    ]:
        res = classify_file_detailed(path)
        assert res.category in (FileCategory.BUILD_ARTIFACT, FileCategory.BINARY), f"Failed for {path}"


def test_06_minified_javascript() -> None:
    """6. Minified JS (.min.js or extreme single-line density) classifies as MINIFIED."""
    # By extension
    res_ext = classify_file_detailed("assets/jquery.min.js")
    assert res_ext.category == FileCategory.MINIFIED
    assert res_ext.reason.startswith("minified_extension")

    # By extreme single line length (> 1000 chars)
    dense_code = "var a=1;" + "function x(){return 42;}" * 100
    res_dense = classify_file_detailed("assets/logic.js", dense_code)
    assert res_dense.category == FileCategory.MINIFIED
    assert res_dense.reason == "content_density_single_line_length"


def test_07_minified_css() -> None:
    """7. Minified CSS (.min.css or high density) classifies as MINIFIED."""
    res = classify_file_detailed("styles/theme.min.css")
    assert res.category == FileCategory.MINIFIED
    assert res.reason.startswith("minified_extension")

    dense_css = "body{margin:0;padding:0;color:#333;font-size:14px;line-height:1.5;}" * 50
    res_dense = classify_file_detailed("styles/custom.css", dense_css)
    assert res_dense.category == FileCategory.MINIFIED
    assert res_dense.reason == "content_density_single_line_length"


def test_08_source_map() -> None:
    """8. Source map (.map) classifies as BUILD_ARTIFACT."""
    res = classify_file_detailed("dist/bundle.js.map")
    assert res.category == FileCategory.BUILD_ARTIFACT
    assert res.reason == "source_map_artifact"


def test_09_vendor_file() -> None:
    """9. Files under vendor/ or third_party/ classify as VENDOR."""
    res1 = classify_file_detailed("vendor/lib.js")
    assert res1.category == FileCategory.VENDOR
    assert res1.reason.startswith("known_vendor_path")

    res2 = classify_file_detailed("third_party/google/protobuf/wire.py")
    assert res2.category == FileCategory.VENDOR
    assert res2.reason.startswith("known_vendor_path")


def test_10_node_modules() -> None:
    """10. Files under node_modules/ classify as VENDOR."""
    res = classify_file_detailed("node_modules/axios/index.js")
    assert res.category == FileCategory.VENDOR
    assert res.reason.startswith("known_vendor_path")


def test_11_binary_files() -> None:
    """11. Binary extensions or null byte signatures classify as BINARY."""
    res_img = classify_file_detailed("static/logo.png")
    assert res_img.category == FileCategory.BINARY
    assert res_img.reason.startswith("binary_extension")

    res_zip = classify_file_detailed("downloads/release.zip")
    assert res_zip.category == FileCategory.BINARY
    assert res_zip.reason.startswith("binary_extension")

    # Null byte in text-looking file
    res_null = classify_file_detailed("data/dump.dat", b"header\x00data\x01bytes")
    assert res_null.category == FileCategory.BINARY
    assert res_null.reason == "binary_null_byte_signature"



def test_12_lockfiles() -> None:
    """12. Lockfiles (package-lock.json, poetry.lock, etc.) classify as CONFIG."""
    for lockfile in [
        "package-lock.json",
        "poetry.lock",
        "yarn.lock",
        "pnpm-lock.yaml",
        "cargo.lock",
    ]:
        res = classify_file_detailed(lockfile)
        assert res.category == FileCategory.CONFIG, f"Failed for {lockfile}"
        assert res.reason == "lockfile_dependency_metadata"


def test_13_config_files() -> None:
    """13. Project configuration files classify as CONFIG."""
    for cfg in [
        "tsconfig.json",
        "pyproject.toml",
        "Dockerfile",
        "Makefile",
        ".gitignore",
        "config.yaml",
    ]:
        res = classify_file_detailed(cfg)
        assert res.category == FileCategory.CONFIG, f"Failed for {cfg}"


def test_14_unknown_file() -> None:
    """14. Files that match no category classify as UNKNOWN."""
    res = classify_file_detailed("data/sample.customext")
    assert res.category == FileCategory.UNKNOWN
    assert res.reason == "unclassified_file_type"


def test_15_conflicting_classification_signals() -> None:
    """15. Deterministic precedence handles conflicting signals correctly:
    - Binary null byte overrides .py extension
    - Build artifact directory overrides source extension
    - Generated banner overrides source extension
    """
    # Source extension with binary bytes
    res_bin = classify_file_detailed("src/module.py", b"\x00\x01\x02")
    assert res_bin.category == FileCategory.BINARY

    # Source extension in dist directory
    res_build = classify_file_detailed("dist/module.py", "def fn(): pass")
    assert res_build.category == FileCategory.BUILD_ARTIFACT

    # Source extension with generated header banner
    res_gen = classify_file_detailed("src/api.py", "# @generated\ndef fn(): pass")
    assert res_gen.category == FileCategory.GENERATED

    # Vendor directory overrides test filename
    res_vendor_test = classify_file_detailed("node_modules/pkg/tests/test_foo.js")
    assert res_vendor_test.category == FileCategory.VENDOR


def test_16_backward_compatibility() -> None:
    """16. Backward compatibility: classify_file returns FileCategory enum that equals GENERATED for legacy code."""
    assert classify_file("src/main.py") == FileCategory.SOURCE
    assert classify_file("tests/test_auth.py") == FileCategory.TEST
    assert classify_file("app.min.js") == FileCategory.MINIFIED
    assert classify_file("app.min.js") == "GENERATED"
    assert classify_file("app.bundle.js") == FileCategory.BUNDLE
    assert classify_file("app.bundle.js") == "GENERATED"
